mport Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
const { ethers } = require("hardhat");

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
//contract address and abi missing
const address = "contract address";
const abi = "abi";

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
document.addEventListener("DOMContentLoaded", function(event) {

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
    if (window.ethereum) {

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
      ethereum.request({ method: "eth_requestAccounts"})
      //"count" ID placeholder must grab from html
      .then(() => document.getElementById("count").click()) 
      .catch((err) => console.error(err.message));

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
      ethereum.on("chainChanged", () => window.location.reload());

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>
      ethereum.on("accountsChanged", (accounts) => {
          if (accounts.length > 0) { 
            console.log(`Using account ${accounts[0]}`)
          } else {
              console.error("0 accounts.");
          }
      });

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      ethereum.on("message", (message) => console.log(message));

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
      ethereum.on("connect", (info) => {
        console.log(`Connected to network ${info}`);
      });

      ethereum.on("disconnect", (error) => {
        console.log(`Disconnected from network ${error}`);
      });

      const provider = new ethers.providers.Web3Provider(window.ethereum);

      const signer = provider.getSigner();

      const contract = new ethers.Contract(address, abi, signer);


    } else {
        console.error("Install MetaMask.");
    }
});
